### ISSUE TITLE
Can not open an xml file

### ISSUE THREAD

**Issue by BrunoAhee** [ajvorobiev/StringForge#36]
On windows 10 after asking to load a file, nothing happens (in zip latest version of StringForge and a folder called "Test"

[http://arma3-tutoriels.fr/StringForge-with-XML.zip](url)

**Comment by ajvorobiev** [comment]
I'll investigate, but I suppose could be to either use of unsupported language or self closing tags `<French />`

**Comment by BrunoAhee** [comment]
I found the mistake : 

2351: | 60 | The reference to entity "amp" must end with the ';' delimiter.

sorry for this issue !
